artifact_location: file:///c:/Users/USER/Desktop/Football_Anal/training/runs/mlflow/0
creation_time: 1714735542533
experiment_id: '0'
last_update_time: 1714735542533
lifecycle_stage: active
name: Default
